version: '3.8'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8001 --workers 3 --timeout 200
    ports:
      - "8001:8001"
    networks:
      - webnet
networks:
  webnet: